.TH cfengine 8 "Maintenance Commands" HiOslo
.SH NAME
cfengine \- network configuration engine
.SH SYNOPSIS

/usr/local/sbin/cfenvgraph [options]


.SH DESCRIPTION
.B cfengine
is a language based system specifically designed
for testing and configuring unix\-like systems attached to
a TCP/IP network. Cfenvd is part of the anomaly detection
subsystem for cfagent.

.B cfenvgraph is a research tool for extracting graphs of the
learned history of system performance from the learned database.
Users are referred to the web page 

.PP
http://www.cfengine.org/confdir/cfenvgraph.html

.PP
for an explanation of this graphical tool.

.SH AUTHOR
Mark Burgess, Oslo University College
.SH INFORMATION
http://www.cfengine.org

